"""empty message

Revision ID: 34635fc9c200
Revises: ca3fb212ea6a
Create Date: 2021-03-14 07:25:32.737868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34635fc9c200'
down_revision = 'ca3fb212ea6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post', sa.String(length=50), nullable=True))
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('posts', 'post')
    # ### end Alembic commands ###
