"""post file id in gdrive

Revision ID: 681580388d9f
Revises: d96697917d8e
Create Date: 2021-03-28 11:08:07.506519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681580388d9f'
down_revision = 'd96697917d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_file_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_file_id')
    # ### end Alembic commands ###
