"""empty message

Revision ID: 7ea78e52249b
Revises: 681580388d9f
Create Date: 2021-03-28 11:36:39.982572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ea78e52249b"
down_revision = "681580388d9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("post_gdrive_id", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "posts", sa.Column("post_gdrive_name", sa.String(length=50), nullable=True)
    )
    op.drop_column("posts", "post_file_id")
    op.drop_column("posts", "post_filename")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "post_filename", sa.VARCHAR(length=5000), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "posts",
        sa.Column(
            "post_file_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("posts", "post_gdrive_name")
    op.drop_column("posts", "post_gdrive_id")
    # ### end Alembic commands ###
