"""google_id and picture in user

Revision ID: b9af22b8d7b8
Revises: ff5e842fce09
Create Date: 2021-04-04 16:17:47.062717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9af22b8d7b8'
down_revision = 'ff5e842fce09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
