"""posts table

Revision ID: ca3fb212ea6a
Revises: 3ee92c2afb63
Create Date: 2021-03-13 16:12:56.706159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca3fb212ea6a"
down_revision = "3ee92c2afb63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column("creation_date", sa.DateTime(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_posts_creation_date"), "posts", ["creation_date"], unique=False
    )
    op.create_index(
        op.f("ix_posts_last_modified"), "posts", ["last_modified"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_last_modified"), table_name="posts")
    op.drop_index(op.f("ix_posts_creation_date"), table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###
