"""empty message

Revision ID: ff5e842fce09
Revises: 7ea78e52249b
Create Date: 2021-03-28 15:05:13.262741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff5e842fce09"
down_revision = "7ea78e52249b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("picture", sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "picture")
    # ### end Alembic commands ###
